fix build under Fedora 38
Building brlaser under Fedora 38 gives the following error in
test/tempfile.h:
error: 'uint8_t' was not declared in this scope

This commit fixes it by explicitly including `cstdin` in the file, so
`uint8_t` is correctly defined there.